// Auto-generated from products.csv. Do not edit by hand.
import type { CatalogProduct } from "./store"

export const catalogProducts: CatalogProduct[] = [
  {
    slug: "tito-s-handmade-vodka-1l-80-proof-buy-online",
    title: "Tito's Handmade Vodka 1L",
    category: "Vodka",
    price: "$27.49",
    badge: "Popular",
    description: "Tito's Handmade Vodka is crafted in small batches from corn, distilled six times for a clean, smooth taste. This 1-liter bottle at 80 proof delivers a gluten-free spirit perfect for cocktails or sipping neat. A versatile, award-winning American vodka.",
    imageUrl: "/images/products/0410_619947000013_titos-handmade-vodka-80.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 1000,
    abv: 40.0,
    vendor: "Tito's",
    displaySize: "1L",
  },
  {
    slug: "jameson-irish-whiskey-750ml-smooth-triple-distilled-blend",
    title: "Jameson Irish Whiskey 750ml",
    category: "Whiskey",
    price: "$31.99",
    badge: "Popular",
    description: "Jameson Irish Whiskey is a smooth, triple-distilled blend of pot still and fine grain whiskeys. Aged in oak casks, it offers balanced notes of vanilla, toasted wood, and sweet spice. Perfect for sipping neat, on the rocks, or in classic cocktails like the Irish Coffee or Whiskey Sour.",
    imageUrl: "/images/products/0434_080432500170_jameson-irish-whiskey.png",
    rating: 4.7,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "Jameson",
    displaySize: "750ml",
  },
  {
    slug: "modelo-especial-24-12-oz-cans-mexican-lager-beer",
    title: "Modelo Especial 24/12 oz Cans",
    category: "Beer",
    price: "$37.57",
    badge: "Popular",
    description: "Modelo Especial is a rich, full-flavored pilsner-style lager with a crisp, refreshing finish. Brewed with premium ingredients, this Mexican beer delivers a smooth taste and golden color. Perfect for any occasion, from casual gatherings to celebrations. Pack includes 24 cans, each 12 oz.",
    imageUrl: "/images/products/0614_080660957760_modelo-especial.png",
    rating: 4.5,
    reviewCount: 192,
    abv: 5,
    vendor: "Modelo",
    displaySize: "24-pack",
  },
  {
    slug: "bud-light-24-pack-12-fl-oz-bottles-288-fl-oz-total",
    title: "Bud Light 24-Pack 12 FL OZ Bottles",
    category: "Beer",
    price: "$32.99",
    badge: "Popular",
    description: "Stock up with Bud Light's 24-pack of 12 fl oz bottles. This light lager delivers a crisp, clean, and refreshing taste with a subtle hop aroma. Perfect for parties, tailgates, or casual get-togethers, it's an easy-drinking classic that pairs well with any occasion. Enjoy the smooth finish and consistent quality of America's favorite light beer.",
    imageUrl: "/images/products/0628_018200533495_bud-light-24-pack-12-fl-oz-bottle.png",
    rating: 4.5,
    reviewCount: 190,
    abv: 5,
    vendor: "Bud",
  },
  {
    slug: "tito-s-handmade-vodka-750ml-gluten-free-craft-vodka",
    title: "Tito's Handmade Vodka 750ml",
    category: "Vodka",
    price: "$20.69",
    badge: "Popular",
    description: "Tito's Handmade Vodka is crafted in small batches from corn, yielding a smooth, clean taste. This 80-proof spirit is naturally gluten-free, making it a versatile choice for cocktails or sipping neat. Distilled in Austin, Texas, it's a premium vodka at an approachable price.",
    imageUrl: "/images/products/0644_619947000020_titos-handmade-vodka-80.png",
    rating: 4.5,
    reviewCount: 190,
    volumeMl: 750,
    abv: 40,
    vendor: "Tito's",
    displaySize: "750ml",
  },
  {
    slug: "modelo-especial-12-pack-bottle-144-fl-oz-mexican-lager",
    title: "Modelo Especial 12-Pack Bottle",
    category: "Beer",
    price: "$20.99",
    badge: "Popular",
    description: "Modelo Especial 12-pack bottles deliver a crisp, refreshing Mexican lager with a smooth finish. Perfect for gatherings, this 144 FL OZ pack offers great value. Enjoy its balanced flavor and golden pour anytime.",
    imageUrl: "/images/products/0682_080660957579_modelo-especial-12-pack-bottle.png",
    rating: 4.4,
    reviewCount: 188,
    abv: 5,
    vendor: "Modelo",
  },
  {
    slug: "kahlua-coffee-liqueur-50ml-mini-bottle",
    title: "Kahlua Coffee Liqueur 50ml Mini Bottle",
    category: "Liqueurs",
    price: "$1.99",
    badge: "Popular",
    description: "Rich, smooth coffee liqueur from Mexico. Perfect for cocktails, baking, or sipping neat. This 50ml mini bottle is ideal for sampling or gifting. Enjoy the classic taste of Kahlua in a convenient small size.",
    imageUrl: "/images/products/0309_089540122748_kahlua-coffee-liqueur.png",
    rating: 3.8,
    reviewCount: 201,
    volumeMl: 50,
    vendor: "Kahlua",
    displaySize: "50ml",
  },
  {
    slug: "bud-light-can-25-oz-crisp-american-lager-buy-online",
    title: "Bud Light Can 25 Oz - Crisp American Lager",
    category: "Beer",
    price: "$3.59",
    badge: "Popular",
    description: "Enjoy the crisp, refreshing taste of Bud Light in a convenient 25 oz can. This light lager is brewed with a blend of barley malts and rice for a clean, smooth finish. Perfect for casual gatherings, tailgates, or relaxing at home. Stock up on this classic American favorite today.",
    imageUrl: "/images/products/0152_018200250019_bud-light-can.png",
    rating: 4.2,
    reviewCount: 213,
    abv: 5,
    vendor: "Bud",
  },
  {
    slug: "jack-daniel-s-black-tennessee-whiskey-375ml",
    title: "Jack Daniel's Black Tennessee Whiskey 375ml",
    category: "Whiskey",
    price: "$12.66",
    badge: "Popular",
    description: "Jack Daniel's Black Tennessee Whiskey is charcoal-mellowed for smoothness. This 375ml bottle offers a classic, full-bodied flavor with notes of caramel, vanilla, and toasted oak, perfect for sipping neat or in cocktails.",
    imageUrl: "/images/products/0102_082184090503_jack-daniel-s-black.png",
    rating: 4.4,
    reviewCount: 216,
    volumeMl: 375,
    abv: 40,
    vendor: "Jack",
    displaySize: "375ml",
  },
  {
    slug: "budweiser-25-oz-can-classic-american-lager",
    title: "Budweiser 25 Oz Can - Classic American Lager",
    category: "Beer",
    price: "$3.59",
    badge: "Popular",
    description: "Enjoy the crisp, smooth taste of Budweiser, America's iconic lager. Brewed with the finest barley malt and a blend of premium hop varieties, this 25 oz can delivers a refreshing, medium-bodied beer perfect for any occasion.",
    imageUrl: "/images/bottle.jpg",
    rating: 4.2,
    reviewCount: 212,
    abv: 5,
    vendor: "Budweiser",
  },
  {
    slug: "johnnie-walker-red-label-375ml-buy-scotch-whisky-online",
    title: "Johnnie Walker Red Label 375ml",
    category: "Whiskey",
    price: "$16.19",
    badge: "Popular",
    description: "Johnnie Walker Red Label is a bold, versatile Scotch whisky with a vibrant blend of light whiskies from Scotland's east coast and peaty west coast malts. Perfect for mixing in classic cocktails like a Whisky Highball or enjoying on the rocks.",
    imageUrl: "/images/products/0112_088110021191_johnnie-walker-red-label.png",
    rating: 4.3,
    reviewCount: 215,
    volumeMl: 375,
    abv: 40,
    vendor: "Johnnie",
    displaySize: "375ml",
  },
  {
    slug: "johnnie-walker-black-label-375ml-premium-blended-scotch-whisky",
    title: "Johnnie Walker Black Label 375ml",
    category: "Whiskey",
    price: "$20.29",
    badge: "Popular",
    description: "Johnnie Walker Black Label is a rich, smooth blended Scotch whisky aged 12 years. With layers of sweet fruit, vanilla, and a whisper of smoke, it’s perfect for sipping neat or in classic cocktails. A timeless choice for any occasion.",
    imageUrl: "/images/products/0146_088110011192_johnnie-walker-black-label.png",
    rating: 4.3,
    reviewCount: 213,
    volumeMl: 375,
    abv: 40,
    vendor: "Johnnie",
    displaySize: "375ml",
  },
  {
    slug: "corona-extra-beer-6-pack-12oz-bottles-buy-online",
    title: "Corona Extra Beer 6-Pack 12oz Bottles",
    category: "Beer",
    price: "$12.29",
    badge: "Popular",
    description: "Enjoy the crisp, refreshing taste of Corona Extra, a classic Mexican lager with a smooth, balanced flavor and a hint of citrus. Perfect for beach days, barbecues, or relaxing at home. This 6-pack of 12oz bottles is ideal for sharing with friends or savoring solo.",
    imageUrl: "/images/products/0187_080660956053_corona-extra.png",
    rating: 4.1,
    reviewCount: 208,
    abv: 5,
    vendor: "Corona",
    displaySize: "6-pack",
  },
  {
    slug: "monster-energy-drink-16oz-can-bold-flavor-big-energy",
    title: "Monster Energy Drink 16oz Can - Bold Flavor, Big Energy",
    category: "Mixers",
    price: "$4.59",
    badge: "Popular",
    description: "Get the iconic Monster Energy boost in a 16oz can. This bold, refreshing energy drink delivers the classic Monster taste and a powerful kick to keep you going through your busiest days or late nights. Perfect for on-the-go fuel.",
    imageUrl: "/images/products/0476_070847037828_monster.png",
    rating: 4.7,
    reviewCount: 196,
    vendor: "Monster",
  },
  {
    slug: "jameson-irish-whiskey-1l-smooth-triple-distilled-whisky",
    title: "Jameson Irish Whiskey 1L",
    category: "Whiskey",
    price: "$43.99",
    badge: "Popular",
    description: "Jameson Irish Whiskey is a classic triple-distilled blend, known for its smooth, balanced character with hints of vanilla, toasted wood, and sweet spice. Perfect for sipping neat, on the rocks, or in cocktails. This 1-liter bottle offers great value for gatherings and home bars.",
    imageUrl: "/images/products/0253_080432500118_jameson-irish-whisky.png",
    rating: 3.9,
    reviewCount: 202,
    volumeMl: 1000,
    abv: 40,
    vendor: "Jameson",
    displaySize: "1L",
  },
  {
    slug: "maker-s-mark-375ml-bourbon-whiskey-smooth-handcrafted",
    title: "Maker's Mark 375ml Bourbon Whiskey",
    category: "Whiskey",
    price: "$18.49",
    badge: "Popular",
    description: "Maker's Mark is a handcrafted Kentucky straight bourbon whiskey, known for its smooth, full-bodied flavor with notes of vanilla, caramel, and oak. Each 375ml bottle is sealed with signature red wax, making it a perfect gift or personal pour for any occasion.",
    imageUrl: "/images/products/0267_085246185001_marker-s-mark.png",
    rating: 3.9,
    reviewCount: 202,
    volumeMl: 375,
    abv: 40,
    vendor: "Maker's",
    displaySize: "375ml",
  },
  {
    slug: "johnnie-walker-black-label-blended-scotch-whisky-750ml",
    title: "Johnnie Walker Black Label Blended Scotch Whisky 750ml",
    category: "Whiskey",
    price: "$41.40",
    badge: "Popular",
    description: "Johnnie Walker Black Label is a premium blended Scotch whisky aged 12 years, offering rich notes of sweet fruit, vanilla, and a signature smoky finish. Perfect for sipping neat or in classic cocktails, this 750ml bottle delivers depth and smoothness for any occasion.",
    imageUrl: "/images/products/0283_088110011307_johnnie-walker-black.png",
    rating: 3.9,
    reviewCount: 202,
    volumeMl: 750,
    abv: 40,
    vendor: "Johnnie",
    displaySize: "750ml",
  },
  {
    slug: "jack-daniel-s-black-tennessee-whiskey-1l",
    title: "Jack Daniel's Black Tennessee Whiskey 1L",
    category: "Whiskey",
    price: "$34.30",
    badge: "Popular",
    description: "Jack Daniel's Black Tennessee Whiskey is charcoal-mellowed for a smooth, distinctive character. This 1L bottle offers rich notes of caramel, vanilla, and toasted oak, with a warm, balanced finish. Perfect for sipping neat or mixing in classic cocktails.",
    imageUrl: "/images/products/0285_082184090442_jack-daniel-s-black.png",
    rating: 3.9,
    reviewCount: 202,
    volumeMl: 1000,
    abv: 40,
    vendor: "Jack",
    displaySize: "1L",
  },
  {
    slug: "fireball-whisky-66pf-1-75-l-cinnamon-whiskey",
    title: "Fireball Whisky 66pf 1.75 L",
    category: "Whiskey",
    price: "$25.19",
    badge: "Popular",
    description: "Fireball Whisky delivers a fiery kick of cinnamon spice with a smooth, sweet finish. This 66-proof cinnamon whisky is perfect for shots, mixing in cocktails, or enjoying straight. The 1.75 L bottle ensures you have plenty for parties and gatherings.",
    imageUrl: "/images/products/0292_088004009281_fireball-whisky-66pf.png",
    rating: 3.9,
    reviewCount: 201,
    volumeMl: 1750,
    abv: 33.0,
    vendor: "Fireball",
    displaySize: "1.75L",
  },
  {
    slug: "fireball-cinnamon-whisky-66pf-1-75l",
    title: "Fireball Cinnamon Whisky 66pf 1.75l",
    category: "Whiskey",
    price: "$25.10",
    badge: "Popular",
    description: "Fireball Cinnamon Whisky delivers a fiery kick of cinnamon with a smooth, sweet finish. This 1.75L bottle at 66 proof is perfect for parties, shots, or mixing into your favorite cocktails. A bold, spicy spirit that’s always a crowd-pleaser.",
    imageUrl: "/images/products/0304_088004026172_fireball-66pf.png",
    rating: 3.9,
    reviewCount: 201,
    volumeMl: 1750,
    abv: 33.0,
    vendor: "Fireball",
    displaySize: "1.75L",
  },
  {
    slug: "jack-daniel-s-black-label-tennessee-whiskey-750ml",
    title: "Jack Daniel's Black Label Tennessee Whiskey 750ml",
    category: "Whiskey",
    price: "$27.03",
    badge: "Popular",
    description: "Jack Daniel's Black Label is the classic Tennessee whiskey, charcoal-mellowed for smoothness. Rich notes of caramel, vanilla, and toasted oak with a warm, balanced finish. Perfect for sipping neat or mixing in timeless cocktails. A true American icon.",
    imageUrl: "/images/products/0337_082184090466_jack-daniel-s-black-label.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Jack",
    displaySize: "750ml",
  },
  {
    slug: "jose-cuervo-tradicional-blanco-tequila-750-ml",
    title: "Jose Cuervo Tradicional Blanco Tequila 750 ml",
    category: "Tequila",
    price: "$26.29",
    badge: "Popular",
    description: "Jose Cuervo Tradicional Blanco is a crisp, 100% blue agave tequila with a smooth, authentic taste. Perfect for margaritas, palomas, or sipping neat, this 750 ml bottle delivers classic Mexican heritage and quality in every pour.",
    imageUrl: "/images/products/0401_811538011426_jose-cuervo-tradicional-blanco.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "Jose",
    displaySize: "750ml",
  },
  {
    slug: "1800-tequila-a-ejo-750ml-premium-aged-tequila",
    title: "1800 Tequila Añejo 750ml",
    category: "Tequila",
    price: "$44.79",
    badge: "Popular",
    description: "1800 Tequila Añejo is a premium 100% blue agave tequila aged in oak barrels for a rich, smooth taste. Notes of vanilla, caramel, and toasted oak make it perfect for sipping neat or in elevated cocktails.",
    imageUrl: "/images/products/0405_811538010030_1800-tequila-a-ejo.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "1800",
    displaySize: "750ml",
  },
  {
    slug: "jose-cuervo-tradicional-reposado-tequila-750-ml",
    title: "Jose Cuervo Tradicional Reposado Tequila 750 ml",
    category: "Tequila",
    price: "$29.19",
    badge: "Popular",
    description: "Jose Cuervo Tradicional Reposado is a 100% blue agave tequila rested in oak barrels for a smooth, balanced taste. Notes of cooked agave, vanilla, and light spice make it perfect for sipping or premium cocktails. A timeless choice for any occasion.",
    imageUrl: "/images/products/0409_811538011372_jose-cuervo-tradicional-repasado.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "Jose",
    displaySize: "750ml",
  },
  {
    slug: "woodford-reserve-distiller-s-select-375ml-premium-bourbon",
    title: "Woodford Reserve Distiller's Select 375ml",
    category: "Whiskey",
    price: "$18.79",
    badge: "Popular",
    description: "Woodford Reserve Distiller's Select is a super-premium Kentucky straight bourbon, crafted in small batches. Rich and complex with notes of dried fruit, vanilla, and toasted oak. Its smooth, full-bodied character makes it perfect for sipping neat or in classic cocktails. A 375ml bottle for those who appreciate exceptional quality.",
    imageUrl: "/images/products/0416_081128011680_woodford-reserve-destiller-s-select.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 375,
    abv: 40,
    vendor: "Woodford",
    displaySize: "375ml",
  },
  {
    slug: "hennessy-vs-cognac-375ml-buy-online",
    title: "Hennessy VS Cognac 375ml",
    category: "Whiskey",
    price: "$20.07",
    badge: "Popular",
    description: "Hennessy VS is a bold, well-balanced cognac with rich fruit notes and a smooth finish. Perfect for sipping neat or mixing in classic cocktails. This 375ml bottle offers a convenient size for trying or gifting.",
    imageUrl: "/images/products/0432_088110150631_hennesy-vs.png",
    rating: 4.7,
    reviewCount: 198,
    volumeMl: 375,
    abv: 40,
    vendor: "Hennessy",
    displaySize: "375ml",
  },
  {
    slug: "johnnie-walker-black-label-50ml-sleeve",
    title: "Johnnie Walker Black Label 50ml Sleeve",
    category: "Whiskey",
    price: "$46.02",
    badge: "Popular",
    description: "Johnnie Walker Black Label is a premium blended Scotch whisky with rich, smooth character. This 50ml sleeve is perfect for sampling or gifting. Enjoy notes of vanilla, dried fruit, and a hint of smoke in every sip.",
    imageUrl: "/images/products/0436_088110011000_jonny-walker-blk-50ml-slvee.png",
    rating: 4.7,
    reviewCount: 198,
    volumeMl: 50,
    abv: 40,
    vendor: "Johnnie",
    displaySize: "50ml",
  },
  {
    slug: "bacardi-superior-white-rum-750ml",
    title: "Bacardi Superior White Rum 750ml",
    category: "Vodka",
    price: "$16.57",
    badge: "Popular",
    description: "Bacardi Superior White Rum is a light, versatile spirit with subtle floral and fruity notes. Perfect for classic cocktails like mojitos and daiquiris, it delivers a smooth, clean finish. Ideal for mixing, this 750ml bottle is a bar essential for any occasion.",
    imageUrl: "/images/products/0458_080480015404_bacardi-rum-superior-80.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "Bacardi",
    displaySize: "750ml",
  },
  {
    slug: "1800-tequila-reposado-750ml-smooth-aged-tequila",
    title: "1800 Tequila Reposado 750ml - Smooth Aged Tequila",
    category: "Tequila",
    price: "$35.99",
    badge: "Popular",
    description: "1800 Tequila Reposado is aged in oak barrels for a smooth, rich taste. Notes of caramel and vanilla complement its agave-forward profile. Perfect for sipping or premium cocktails. 750ml bottle.",
    imageUrl: "/images/products/0462_811538010238_1800-tequila-reposado.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "1800",
    displaySize: "750ml",
  },
  {
    slug: "jack-daniel-s-tennessee-apple-whiskey-750ml",
    title: "Jack Daniel's Tennessee Apple Whiskey 750ml",
    category: "Whiskey",
    price: "$27.03",
    badge: "Popular",
    description: "Jack Daniel's Tennessee Apple blends their classic Old No. 7 with crisp apple liqueur for a smooth, refreshing finish. Perfect for shots or mixing in cocktails, this 750ml bottle delivers a sweet yet balanced whiskey experience.",
    imageUrl: "/images/products/0447_082184004371_jack-daniel-s-tenn-apple.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "Jack",
    displaySize: "750ml",
  },
  {
    slug: "white-claw-hard-seltzer-19-2-oz-can",
    title: "White Claw Hard Seltzer 19.2 oz Can",
    category: "Beer",
    price: "$3.89",
    badge: "Popular",
    description: "White Claw Hard Seltzer delivers a crisp, refreshing taste with a hint of fruit flavor. This 19.2 oz single can is perfect for on-the-go enjoyment. Made with seltzer water, gluten-free alcohol, and natural flavors, it's a light, bubbly choice for any occasion.",
    imageUrl: "/images/products/0619_635985803690_white-claw.png",
    rating: 4.5,
    reviewCount: 191,
    abv: 5,
    vendor: "White",
  },
  {
    slug: "white-claw-hard-seltzer-19-2-oz-can-2",
    title: "White Claw Hard Seltzer 19.2 oz Can",
    category: "Beer",
    price: "$3.89",
    badge: "Popular",
    description: "White Claw Hard Seltzer in a 19.2 oz single can. A refreshing, gluten-free spiked sparkling water with a clean, crisp taste. Perfect for casual gatherings or relaxing at home. Low calorie and low sugar. Enjoy responsibly.",
    imageUrl: "/images/products/0620_635985802136_white-claw.png",
    rating: 4.5,
    reviewCount: 191,
    abv: 5,
    vendor: "White",
  },
  {
    slug: "patron-silver-tequila-80-proof-750ml",
    title: "Patron Silver Tequila 80 Proof 750ml",
    category: "Tequila",
    price: "$51.99",
    badge: "Popular",
    description: "Patron Silver Tequila is a premium, crystal-clear spirit with a smooth, fresh taste and a hint of citrus. Perfect for sipping neat or mixing in cocktails like margaritas. This 750ml bottle at 80 proof delivers consistent quality for any occasion.",
    imageUrl: "/images/products/0607_721733000029_patron-silver-tequila-80.png",
    rating: 4.6,
    reviewCount: 192,
    volumeMl: 750,
    abv: 40.0,
    vendor: "Patron",
    displaySize: "750ml",
  },
  {
    slug: "tito-s-handmade-vodka-375ml-gluten-free-80-proof",
    title: "Tito's Handmade Vodka 375ml",
    category: "Vodka",
    price: "$11.39",
    badge: "Popular",
    description: "Tito's Handmade Vodka is crafted in small batches from corn, yielding a smooth, clean taste. This 375ml bottle offers the same award-winning, gluten-free spirit, perfect for cocktails or sipping neat. Distilled six times for exceptional purity.",
    imageUrl: "/images/products/0610_619947000051_titos-handmade-vodka-80.png",
    rating: 4.6,
    reviewCount: 192,
    volumeMl: 375,
    abv: 40,
    vendor: "Tito's",
    displaySize: "375ml",
  },
  {
    slug: "dr-pepper-2-liter-bottle-classic-23-flavor-soda",
    title: "Dr Pepper 2 Liter Bottle",
    category: "Mixers",
    price: "$5.39",
    badge: "Popular",
    description: "Enjoy the unique, bold taste of Dr Pepper in a convenient 2-liter bottle. This iconic soda blends 23 flavors for a refreshing, one-of-a-kind experience. Perfect for parties, meals, or anytime you crave a crisp, satisfying drink. Stock up on this timeless favorite.",
    imageUrl: "/images/products/0650_078000082463_dr-pepper.png",
    rating: 4.5,
    reviewCount: 189,
    volumeMl: 2000,
    vendor: "Dr",
    displaySize: "2L",
  },
  {
    slug: "smirnoff-vodka-1-75l-smooth-classic",
    title: "Smirnoff Vodka 1.75l",
    category: "Vodka",
    price: "$27.39",
    badge: "Popular",
    description: "Smirnoff Vodka is a classic, triple-distilled spirit known for its smooth, clean taste. Perfect for mixing in cocktails or enjoying on the rocks, this 1.75L bottle offers great value for parties and gatherings. A versatile staple for any home bar.",
    imageUrl: "/images/products/0658_082000727606_smirnoff.png",
    rating: 4.5,
    reviewCount: 189,
    volumeMl: 1750,
    abv: 40,
    vendor: "Smirnoff",
    displaySize: "1.75L",
  },
  {
    slug: "red-bull-energy-drink-20oz-can-12-pack-case",
    title: "Red Bull Energy Drink 20oz Can (12-Pack Case)",
    category: "Energy Drink",
    price: "$5.58",
    badge: "Popular",
    description: "Get the wings you need with Red Bull Energy Drink in a 20oz can. This 12-pack case delivers the iconic taste and functional boost for work, study, or play. Stock up on the world's leading energy drink, perfect for convenience and on-the-go refreshment.",
    imageUrl: "/images/products/1111_611269134551_red-bull-20oz-can-12-case.png",
    rating: 4.3,
    reviewCount: 183,
    vendor: "Red",
  },
  {
    slug: "coors-light-24oz-can-crisp-refreshing-light-beer",
    title: "Coors Light 24oz Can - Crisp, Refreshing Light Beer",
    category: "Beer",
    price: "$2.99",
    badge: "Popular",
    description: "Coors Light delivers crisp, refreshing taste with a light body and clean finish. This 24oz can is cold lagered, cold filtered, and cold packaged for an exceptionally smooth beer. Perfect for casual gatherings, tailgates, or relaxing at home. Enjoy the Rocky Mountain refreshment anytime.",
    imageUrl: "/images/products/1130_071990300654_coors-light.png",
    rating: 4.2,
    reviewCount: 183,
    abv: 5,
    vendor: "Coors",
  },
  {
    slug: "tito-s-handmade-vodka-50ml-mini-bottle",
    title: "Tito's Handmade Vodka 50ml Mini Bottle",
    category: "Vodka",
    price: "$1.89",
    badge: "Popular",
    description: "Tito's Handmade Vodka in a convenient 50ml mini bottle. Crafted in Austin, Texas, from corn and naturally gluten-free. Smooth, clean taste perfect for sampling, gifting, or travel. Enjoy the award-winning quality of Tito's in a portable size.",
    imageUrl: "/images/products/0003_619947000068_titos-50ml.png",
    rating: 4.4,
    reviewCount: 248,
    volumeMl: 50,
    abv: 40,
    vendor: "Tito's",
    displaySize: "50ml",
  },
  {
    slug: "crown-royal-canadian-whisky-750ml",
    title: "Crown Royal Canadian Whisky 750ml",
    category: "Whiskey",
    price: "$30.99",
    badge: "Popular",
    description: "Smooth and regal, Crown Royal Canadian Whisky delivers a rich, velvety blend with notes of vanilla, oak, and subtle fruit. Perfect for sipping neat or mixing in classic cocktails, this 750ml bottle brings a touch of luxury to any occasion.",
    imageUrl: "/images/products/0025_087000007253_crown-royal-canadian.png",
    rating: 4.6,
    reviewCount: 224,
    volumeMl: 750,
    abv: 40,
    vendor: "Crown",
    displaySize: "750ml",
  },
  {
    slug: "crown-royal-canadian-whisky-375-ml",
    title: "Crown Royal Canadian Whisky 375 ml",
    category: "Whiskey",
    price: "$14.69",
    badge: "Popular",
    description: "Crown Royal Canadian Whisky offers a smooth, rich blend with notes of vanilla and oak. Perfect for sipping neat or in classic cocktails. This 375 ml bottle is ideal for gifting or enjoying at home.",
    imageUrl: "/images/products/0036_087000007604_crown-royal.png",
    rating: 4.6,
    reviewCount: 224,
    volumeMl: 375,
    abv: 40,
    vendor: "Crown",
    displaySize: "375ml",
  },
  {
    slug: "crown-royal-200ml-canadian-whisky-smooth-regal",
    title: "Crown Royal 200ml",
    category: "Whiskey",
    price: "$9.19",
    badge: "Popular",
    description: "Crown Royal Canadian whisky in a 200ml bottle. Smooth and regal, with a rich, creamy vanilla and oak flavor. Perfect for sipping neat or mixing in classic cocktails. A timeless choice for any occasion.",
    imageUrl: "/images/products/0034_087000007277_crown-royal.png",
    rating: 4.6,
    reviewCount: 224,
    volumeMl: 200,
    abv: 40,
    vendor: "Crown",
    displaySize: "200ml",
  },
  {
    slug: "jack-daniel-s-black-tennessee-whiskey-200ml",
    title: "Jack Daniel's Black Tennessee Whiskey 200ml",
    category: "Whiskey",
    price: "$8.49",
    badge: "Popular",
    description: "Jack Daniel's Black Tennessee Whiskey in a convenient 200ml bottle. Smooth, charcoal-mellowed character with notes of caramel, vanilla, and toasted oak. Perfect for sipping neat, on the rocks, or in classic cocktails. A timeless American icon.",
    imageUrl: "/images/products/0041_082184090527_jack-daniel-s-black.png",
    rating: 4.6,
    reviewCount: 224,
    volumeMl: 200,
    abv: 40,
    vendor: "Jack",
    displaySize: "200ml",
  },
  {
    slug: "fireball-cinnamon-whisky-50ml-mini-bottle",
    title: "Fireball Cinnamon Whisky 50ml Mini Bottle",
    category: "Whiskey",
    price: "$0.99",
    badge: "Popular",
    description: "Fireball Cinnamon Whisky delivers a fiery kick of cinnamon with a smooth whisky base. This 50ml mini bottle is perfect for trying, gifting, or on-the-go enjoyment. Great for shots, mixing, or adding a spicy twist to your favorite cocktails.",
    imageUrl: "/images/products/0072_088004144708_fireball-cinnamon-whisky.png",
    rating: 4.4,
    reviewCount: 218,
    volumeMl: 50,
    abv: 40,
    vendor: "Fireball",
    displaySize: "50ml",
  },
  {
    slug: "fireball-whisky-200ml-cinnamon-whiskey",
    title: "Fireball Whisky 200ml",
    category: "Whiskey",
    price: "$4.49",
    badge: "Popular",
    description: "Fireball Whisky delivers a fiery kick of cinnamon with a smooth, sweet finish. This 200ml bottle is perfect for parties, shots, or mixing into your favorite cocktails. Enjoy the bold, spicy flavor that has made Fireball a cult favorite.",
    imageUrl: "/images/products/0125_088004144739_fireball-whisky.png",
    rating: 4.3,
    reviewCount: 214,
    volumeMl: 200,
    abv: 40,
    vendor: "Fireball",
    displaySize: "200ml",
  },
  {
    slug: "fireball-whisky-375ml-cinnamon-whiskey-liqueur",
    title: "Fireball Whisky 375ml - Cinnamon Whiskey Liqueur",
    category: "Whiskey",
    price: "$5.92",
    badge: "Popular",
    description: "Fireball Whisky delivers a fiery kick of cinnamon spice in a smooth, easy-drinking liqueur. Perfect for shots, cocktails, or sipping straight from the fridge. This 375ml bottle is great for parties or trying something new.",
    imageUrl: "/images/products/0162_088004144722_fireball-whisky.png",
    rating: 4.2,
    reviewCount: 212,
    volumeMl: 375,
    abv: 40,
    vendor: "Fireball",
    displaySize: "375ml",
  },
  {
    slug: "buffalo-trace-bourbon-750ml",
    title: "Buffalo Trace Bourbon 750ml",
    category: "Whiskey",
    price: "$29.99",
    badge: "Popular",
    description: "Buffalo Trace Kentucky Straight Bourbon Whiskey in a 750ml bottle. Distilled, aged, and bottled at the Buffalo Trace Distillery, this bourbon offers a smooth, complex flavor with notes of vanilla, toffee, and spice. Perfect for sipping neat or in classic cocktails.",
    imageUrl: "/images/products/0023_080244009236_buffalo-trace.png",
    rating: 4.6,
    reviewCount: 224,
    volumeMl: 750,
    abv: 40,
    vendor: "Buffalo",
    displaySize: "750ml",
  },
  {
    slug: "fireball-whisky-50ml-cinnamon-whiskey-mini-bottle",
    title: "Fireball Whisky 50ml - Cinnamon Whiskey Mini Bottle",
    category: "Whiskey",
    price: "$5.99",
    badge: "Popular",
    description: "Fireball Cinnamon Whisky in a convenient 50ML mini bottle. Smooth whisky with a fiery kick of cinnamon spice. Perfect for parties, gifting, or trying before buying a full size. Enjoy the bold, sweet heat that's made Fireball a favorite shot and mixer worldwide.",
    imageUrl: "/images/products/0045_088004029227_fireball-whisky.png",
    rating: 4.6,
    reviewCount: 222,
    volumeMl: 50,
    abv: 40,
    vendor: "Fireball",
    displaySize: "50ml",
  },
  {
    slug: "fireball-whisky-50ml-cinnamon-whiskey-mini-bottle-2",
    title: "Fireball Whisky 50ml - Cinnamon Whiskey Mini Bottle",
    category: "Whiskey",
    price: "$7.99",
    badge: "Popular",
    description: "Fireball Whisky delivers a fiery kick of cinnamon spice in a smooth, easy-drinking whisky base. This 50ml mini bottle is perfect for sampling, gifting, or enjoying on the go. A bold, sweet, and warming shot that’s a party favorite.",
    imageUrl: "/images/products/0078_088004020491_fireball-whisky.png",
    rating: 4.4,
    reviewCount: 218,
    volumeMl: 50,
    abv: 40,
    vendor: "Fireball",
    displaySize: "50ml",
  },
  {
    slug: "fireball-whisky-750ml-cinnamon-whiskey",
    title: "Fireball Whisky 750ml - Cinnamon Whiskey",
    category: "Whiskey",
    price: "$14.62",
    badge: "Popular",
    description: "Fireball Whisky delivers a fiery kick of cinnamon spice with a smooth, sweet finish. Perfect for shots, cocktails, or sipping straight, this 750ml bottle brings the heat to any party. A bold, crowd-pleasing choice for those who love a little adventure in their glass.",
    imageUrl: "/images/products/0090_088004146689_fireball-whisky.png",
    rating: 4.4,
    reviewCount: 217,
    volumeMl: 750,
    abv: 40,
    vendor: "Fireball",
    displaySize: "750ml",
  },
  {
    slug: "fireball-cinnamon-whisky-750ml-best-price",
    title: "Fireball Cinnamon Whisky 750ml",
    category: "Whiskey",
    price: "$14.59",
    badge: "Popular",
    description: "Fireball Cinnamon Whisky delivers a fiery kick of cinnamon with a smooth, sweet finish. Perfect for shots, cocktails, or sipping straight. This 750ml bottle brings the heat to any party or gathering. A bold, spicy spirit that's easy to enjoy and always a crowd-pleaser.",
    imageUrl: "/images/products/0094_088004144692_fireball-whsky.png",
    rating: 4.4,
    reviewCount: 217,
    volumeMl: 750,
    abv: 40,
    vendor: "Fireball",
    displaySize: "750ml",
  },
  {
    slug: "jameson-irish-whiskey-375-ml-smooth-triple-distilled",
    title: "Jameson Irish Whiskey 375 ml - Smooth Triple-Distilled",
    category: "Whiskey",
    price: "$18.89",
    badge: "Popular",
    description: "Jameson Irish Whiskey is triple-distilled for exceptional smoothness. This 375 ml bottle offers a balanced blend of spicy, nutty, and vanilla notes with a hint of sweet sherry. Perfect for sipping neat, on the rocks, or in classic cocktails like the Irish Mule.",
    imageUrl: "/images/products/0098_080432500149_jameson-irish.png",
    rating: 4.4,
    reviewCount: 216,
    volumeMl: 375,
    abv: 40,
    vendor: "Jameson",
    displaySize: "375ml",
  },
  {
    slug: "corona-familiar-32oz-bottle-crisp-mexican-lager",
    title: "Corona Familiar 32oz Bottle - Crisp Mexican Lager",
    category: "Beer",
    price: "$4.29",
    badge: "Popular",
    description: "Corona Familiar 32oz bottle delivers the same crisp, refreshing taste of Corona in a larger format perfect for sharing. This Mexican lager is light-bodied with a smooth finish, ideal for casual gatherings or pairing with lime and your favorite foods.",
    imageUrl: "/images/products/0215_080660956831_corona-familiar.png",
    rating: 4.0,
    reviewCount: 206,
    abv: 5,
    vendor: "Corona",
  },
  {
    slug: "monster-energy-drink-16oz-can-bold-energy-boost",
    title: "Monster Energy Drink 16oz Can - Bold Energy Boost",
    category: "Mixers",
    price: "$3.59",
    badge: "Popular",
    description: "Unleash the beast with Monster Energy Drink in a 16oz can. This iconic energy blend delivers a powerful, smooth flavor and the energy lift you need to conquer your day. Perfect for on-the-go fuel, gaming sessions, or late-night work. Grab a cold can and charge ahead.",
    imageUrl: "/images/products/0203_070847005070_monster-energy-drink.png",
    rating: 4.0,
    reviewCount: 207,
    vendor: "Monster",
  },
  {
    slug: "bacardi-gold-rum-80-proof-375ml",
    title: "Bacardi Gold Rum 80 Proof 375ml",
    category: "Alcohol",
    price: "$8.29",
    badge: "Popular",
    description: "Bacardi Gold Rum is a smooth, light-bodied rum with subtle vanilla and almond notes. Aged in oak barrels for a mellow character, it’s perfect for classic cocktails like Cuba Libre or a refreshing rum and cola. Enjoy the quality and heritage of the world’s most awarded rum.",
    imageUrl: "/images/products/0235_080480025601_bacardi-rum-gold-80.png",
    rating: 3.9,
    reviewCount: 204,
    volumeMl: 375,
    vendor: "Bacardi",
    displaySize: "375ml",
  },
  {
    slug: "western-son-vodka-1-75l-smooth-american-vodka",
    title: "Western Son Vodka 1.75l",
    category: "Vodka",
    price: "$20.89",
    badge: "Popular",
    description: "Western Son Vodka delivers a clean, smooth taste crafted from American corn. Distilled ten times for exceptional purity, it’s perfect for mixing in cocktails or enjoying on the rocks. This 1.75L bottle offers great value for parties and everyday sipping.",
    imageUrl: "/images/products/0312_856417003024_western-son-vodka.png",
    rating: 3.8,
    reviewCount: 201,
    volumeMl: 2,
    abv: 40,
    vendor: "Western",
    displaySize: "2ml",
  },
  {
    slug: "mountain-dew-20-oz-bottle-citrus-soda",
    title: "Mountain Dew 20 oz Bottle - Citrus Soda",
    category: "Mixers",
    price: "$1.98",
    badge: "Popular",
    description: "Quench your thirst with the bold, citrus taste of Mountain Dew. This 20 oz bottle delivers the iconic, energizing flavor you love, perfect for on-the-go refreshment. Enjoy the crisp, sweet, and tangy soda that stands out from the rest.",
    imageUrl: "/images/products/0519_012000001314_mountain-dew.png",
    rating: 4.6,
    reviewCount: 195,
    vendor: "Mountain",
  },
  {
    slug: "fanta-orange-20-fl-oz-refreshing-citrus-soda",
    title: "Fanta Orange 20 FL OZ - Refreshing Citrus Soda",
    category: "Mixers",
    price: "$2.25",
    badge: "Popular",
    description: "Quench your thirst with the bold, fruity taste of Fanta Orange. This 20 FL OZ bottle delivers a bubbly, caffeine-free citrus refreshment perfect for any occasion. Enjoy the classic, vibrant orange flavor that's been a favorite for generations. Great chilled or over ice.",
    imageUrl: "/images/products/0520_049000019162_fanta-orange.png",
    rating: 4.6,
    reviewCount: 195,
    vendor: "Fanta",
  },
  {
    slug: "pepsi-cola-20-oz-bottle-crisp-refreshing-soda",
    title: "Pepsi Cola 20 oz Bottle - Crisp & Refreshing Soda",
    category: "Mixers",
    price: "$2.25",
    badge: "Popular",
    description: "Enjoy the bold, refreshing taste of Pepsi Cola in a convenient 20 oz bottle. Perfectly carbonated with a crisp cola flavor, it's an ideal companion for meals, snacks, or on-the-go refreshment. Stock up today for your next gathering or quick thirst quencher.",
    imageUrl: "/images/products/0521_012000001291_pepsi-cola.png",
    rating: 4.6,
    reviewCount: 195,
    vendor: "Pepsi",
  },
  {
    slug: "tullamore-dew-irish-whiskey-750ml",
    title: "Tullamore Dew Irish Whiskey 750ml",
    category: "Whiskey",
    price: "$28.29",
    badge: "Popular",
    description: "Tullamore Dew Irish Whiskey is a smooth and gentle triple-distilled blend, offering a perfect balance of spicy, fruity, and malty notes. Its signature triple blend of pot still, malt, and grain whiskeys delivers a warm, complex flavor with a soft, lingering finish. Ideal for sipping neat or in classic cocktails.",
    imageUrl: "/images/products/0266_083664872466_tullamore-dew-750ml.png",
    rating: 3.9,
    reviewCount: 202,
    volumeMl: 750,
    abv: 40,
    vendor: "Tullamore",
    displaySize: "750ml",
  },
  {
    slug: "jim-beam-bourbon-4-year-80-proof-50ml-pet-bottle",
    title: "Jim Beam Bourbon 4 Year 80 Proof 50ml PET Bottle",
    category: "Whiskey",
    price: "$0.99",
    badge: "Popular",
    description: "Jim Beam Kentucky Straight Bourbon Whiskey, aged 4 years in new charred oak barrels. Smooth and mellow with notes of vanilla, caramel, and oak. Perfect for sipping neat or mixing in classic cocktails. Convenient 50ml PET travel-friendly bottle.",
    imageUrl: "/images/products/0303_080686001904_jim-beam-bourbon-4yr-80-10p-pet.png",
    rating: 3.9,
    reviewCount: 201,
    volumeMl: 50,
    abv: 40,
    vendor: "Jim",
    displaySize: "50ml",
  },
  {
    slug: "jack-daniel-s-tennessee-fire-cinnamon-whiskey-750ml",
    title: "Jack Daniel's Tennessee Fire Cinnamon Whiskey 750ml",
    category: "Whiskey",
    price: "$27.03",
    badge: "Popular",
    description: "Jack Daniel's Tennessee Fire blends smooth Jack Daniel's Old No. 7 with a fiery cinnamon liqueur. The result is a bold, spicy whiskey with a warm, sweet finish. Perfect for shots, mixing into cocktails, or enjoying straight. 750ml bottle.",
    imageUrl: "/images/products/0307_082184001172_jack-daniel-s-tenn-fire.png",
    rating: 3.9,
    reviewCount: 201,
    volumeMl: 750,
    abv: 40,
    vendor: "Jack",
    displaySize: "750ml",
  },
  {
    slug: "johnnie-walker-double-black-blended-scotch-whisky-1l",
    title: "Johnnie Walker Double Black Blended Scotch Whisky 1L",
    category: "Whiskey",
    price: "$50.69",
    badge: "Popular",
    description: "Johnnie Walker Double Black is a rich, smoky blend crafted for depth and intensity. Aged in charred oak casks, it delivers layers of sweet vanilla, dried fruit, and a lingering peaty finish. Perfect for sipping neat or in a bold cocktail.",
    imageUrl: "/images/products/0311_088076177819_johnnie-walker-double-black.png",
    rating: 3.8,
    reviewCount: 201,
    volumeMl: 1000,
    abv: 40,
    vendor: "Johnnie",
    displaySize: "1L",
  },
  {
    slug: "7-up-20-oz-bottle-crisp-lemon-lime-soda",
    title: "7 UP 20 OZ Bottle - Crisp Lemon-Lime Soda",
    category: "Mixers",
    price: "$1.98",
    badge: "Popular",
    description: "Quench your thirst with the crisp, refreshing taste of 7 UP. This 20 oz bottle delivers the classic lemon-lime flavor you love, perfect for enjoying on its own or as a mixer. A timeless soda with a clean, bubbly finish.",
    imageUrl: "/images/products/0536_078000001617_7-up.png",
    rating: 4.6,
    reviewCount: 194,
    vendor: "7",
  },
  {
    slug: "jim-beam-black-7-year-bourbon-50ml-pet-bottle",
    title: "Jim Beam Black 7 Year Bourbon 50ml PET Bottle",
    category: "Whiskey",
    price: "$1.99",
    badge: "Popular",
    description: "Jim Beam Black is a premium bourbon aged 7 years for a smooth, full-bodied character. This 50ml PET bottle offers rich caramel and oak notes, perfect for sipping neat or in classic cocktails. A convenient travel size from the world’s best-selling bourbon brand.",
    imageUrl: "/images/products/0315_080686007715_jim-beam-bbn-black-7y-90-pet-10p.png",
    rating: 3.8,
    reviewCount: 200,
    volumeMl: 50,
    abv: 40,
    vendor: "Jim",
    displaySize: "50ml",
  },
  {
    slug: "svedka-vodka-80-proof-750ml-smooth-swedish-vodka",
    title: "Svedka Vodka 80 Proof 750ml - Smooth Swedish Vodka",
    category: "Vodka",
    price: "$12.49",
    badge: "Popular",
    description: "Svedka Vodka 80 proof is a crisp, clean Swedish vodka distilled five times for exceptional smoothness. Perfect for cocktails or sipping neat, this 750ml bottle offers premium quality at an affordable price. Enjoy its subtle grain character and versatile mixability.",
    imageUrl: "/images/products/0308_088004070922_svedka-vodka-80.png",
    rating: 3.8,
    reviewCount: 201,
    volumeMl: 750,
    abv: 40.0,
    vendor: "Svedka",
    displaySize: "750ml",
  },
  {
    slug: "don-julio-blanco-tequila-375ml-premium-silver-tequila",
    title: "Don Julio Blanco Tequila 375ml",
    category: "Tequila",
    price: "$24.64",
    badge: "Popular",
    description: "Don Julio Blanco is a crisp, clean silver tequila with notes of citrus and agave. Perfect for margaritas or sipping neat, this 375ml bottle offers premium quality in a convenient size. Enjoy the smooth, balanced taste of one of Mexico's finest tequilas.",
    imageUrl: "/images/products/0318_674545000599_don-julio-blanco.png",
    rating: 3.8,
    reviewCount: 200,
    volumeMl: 375,
    abv: 40,
    vendor: "Don",
    displaySize: "375ml",
  },
  {
    slug: "old-forester-100-proof-bourbon-750ml",
    title: "Old Forester 100 Proof Bourbon 750ml",
    category: "Whiskey",
    price: "$26.69",
    badge: "Popular",
    description: "Old Forester 100 Proof delivers bold, full-bodied bourbon with rich caramel, spice, and oak notes. Bottled at 100 proof, it honors a historic recipe for a smooth yet robust sipping experience. Perfect neat, on the rocks, or in classic cocktails.",
    imageUrl: "/images/products/0329_081128001063_old-forester-st-100p.png",
    rating: 3.8,
    reviewCount: 200,
    volumeMl: 750,
    abv: 50.0,
    vendor: "Old",
    displaySize: "750ml",
  },
  {
    slug: "skrewball-peanut-butter-whiskey-750ml",
    title: "Skrewball Peanut Butter Whiskey 750ml",
    category: "Whiskey",
    price: "$24.69",
    badge: "Popular",
    description: "Skrewball Peanut Butter Whiskey delivers a unique blend of smooth whiskey and rich peanut butter flavor. Perfect for sipping neat, on the rocks, or in creative cocktails. This 750ml bottle offers a fun twist on traditional whiskey, appealing to adventurous drinkers and peanut butter lovers alike.",
    imageUrl: "/images/products/0330_860265002405_skrewball-pn-whisky.png",
    rating: 3.8,
    reviewCount: 200,
    volumeMl: 750,
    abv: 40,
    vendor: "Skrewball",
    displaySize: "750ml",
  },
  {
    slug: "crown-royal-chocolate-whisky-750-ml",
    title: "Crown Royal Chocolate Whisky 750 ml",
    category: "Whiskey",
    price: "$30.99",
    badge: "Popular",
    description: "Crown Royal Chocolate blends the signature smoothness of Crown Royal with rich chocolate flavor. This 750 ml bottle offers a velvety, indulgent taste perfect for sipping neat or in cocktails. A delightful treat for whisky lovers seeking a sweet twist.",
    imageUrl: "/images/products/0331_082000811053_crown-royal-chocolate.png",
    rating: 3.8,
    reviewCount: 200,
    volumeMl: 750,
    abv: 40,
    vendor: "Crown",
    displaySize: "750ml",
  },
  {
    slug: "dr-pepper-20-fl-oz-classic-soda",
    title: "Dr Pepper 20 FL OZ - Classic Soda",
    category: "Mixers",
    price: "$1.98",
    badge: "Popular",
    description: "Enjoy the unique, bold taste of Dr Pepper, a beloved soda with a signature blend of 23 flavors. This 20 FL OZ bottle delivers a refreshing, crisp experience perfect for any occasion. Stock up on this classic favorite.",
    imageUrl: "/images/products/0553_078000082401_dr-pepper.png",
    rating: 4.6,
    reviewCount: 193,
    vendor: "Dr",
  },
  {
    slug: "coca-cola-20-fl-oz-bottle-classic-cola-refreshment",
    title: "Coca-Cola 20 FL OZ Bottle",
    category: "Mixers",
    price: "$2.25",
    badge: "Popular",
    description: "Enjoy the crisp, refreshing taste of Coca-Cola in a convenient 20 FL OZ bottle. Perfect for on-the-go moments, this classic cola delivers the great flavor you love. Stock up today for parties, meals, or a quick pick-me-up.",
    imageUrl: "/images/products/0554_049000000443_coca-cola.png",
    rating: 4.6,
    reviewCount: 193,
    vendor: "Coca-Cola",
  },
  {
    slug: "sprite-20-oz-bottle-crisp-lemon-lime-soda",
    title: "Sprite 20 oz Bottle - Crisp Lemon-Lime Soda",
    category: "Mixers",
    price: "$2.25",
    badge: "Popular",
    description: "Quench your thirst with the crisp, refreshing taste of Sprite. This 20 oz bottle delivers the iconic lemon-lime flavor you love, perfect for on-the-go refreshment. Caffeine-free and made with natural flavors, it's a bubbly treat for any occasion.",
    imageUrl: "/images/products/0555_049000007640_sprite.png",
    rating: 4.6,
    reviewCount: 193,
    vendor: "Sprite",
  },
  {
    slug: "herradura-silver-tequila-1l-buy-online",
    title: "Herradura Silver Tequila 1L",
    category: "Tequila",
    price: "$49.99",
    badge: "Popular",
    description: "Herradura Silver is a crisp, 100% blue agave tequila with a smooth, clean taste. Aged 45 days in oak, it offers notes of cooked agave, citrus, and a hint of vanilla. Perfect for sipping or elevating your favorite cocktails.",
    imageUrl: "/images/products/0347_744607050401_herradura-silver.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 1000,
    abv: 40,
    vendor: "Herradura",
    displaySize: "1L",
  },
  {
    slug: "ketel-one-vodka-375ml-smooth-dutch-vodka",
    title: "Ketel One Vodka 375ml",
    category: "Vodka",
    price: "$11.79",
    badge: "Popular",
    description: "Ketel One Vodka is a premium Dutch vodka distilled from 100% wheat in copper pot stills. Crisp, smooth, and refined with a subtle citrus and honey finish. Perfect for martinis or sipping neat. 375ml bottle.",
    imageUrl: "/images/products/0353_085156122158_ketel-one-vodka.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 375,
    abv: 40,
    vendor: "Ketel",
    displaySize: "375ml",
  },
  {
    slug: "1800-blanco-tequila-375ml-smooth-premium-silver-tequila",
    title: "1800 Blanco Tequila 375ml",
    category: "Tequila",
    price: "$15.49",
    badge: "Popular",
    description: "1800 Blanco is a crystal-clear, premium tequila made from 100% blue agave. Its smooth, balanced flavor features hints of sweet agave, citrus, and a peppery finish. Perfect for sipping neat or mixing in margaritas and cocktails. This 375ml bottle is ideal for trying or gifting.",
    imageUrl: "/images/products/0359_811538010122_1800-blanco.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 375,
    abv: 40,
    vendor: "1800",
    displaySize: "375ml",
  },
  {
    slug: "patron-tequila-silver-80-375-ml",
    title: "Patron Tequila Silver 80 375 ml",
    category: "Tequila",
    price: "$24.09",
    badge: "Popular",
    description: "Patron Tequila Silver 80 is a premium, crystal-clear tequila with a smooth, fresh taste. Handcrafted from 100% Weber Blue Agave, it offers a crisp, citrusy flavor with a light pepper finish. Perfect for sipping neat or mixing in classic cocktails like margaritas. 375 ml bottle.",
    imageUrl: "/images/products/0364_721733000944_patron-tequila-silver-80.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 375,
    abv: 40,
    vendor: "Patron",
    displaySize: "375ml",
  },
  {
    slug: "patron-a-ejo-tequila-750ml-premium-aged-tequila",
    title: "Patron Añejo Tequila 750ml",
    category: "Tequila",
    price: "$58.59",
    badge: "Popular",
    description: "Patron Añejo is a premium tequila aged in oak barrels for a smooth, complex taste. Notes of vanilla, dried fruit, and spice make it perfect for sipping neat or elevating classic cocktails. This 750ml bottle delivers exceptional quality for any occasion.",
    imageUrl: "/images/products/0365_721733000012_patron-teq-a-ejo.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Patron",
    displaySize: "750ml",
  },
  {
    slug: "patron-reposado-tequila-750ml-80-proof",
    title: "Patron Reposado Tequila 750ml",
    category: "Tequila",
    price: "$53.99",
    badge: "Popular",
    description: "Patron Reposado is aged in oak barrels for a smooth, balanced taste with hints of agave and light oak. Perfect for sipping or premium cocktails, this 80-proof tequila comes in a 750ml bottle, ideal for any occasion.",
    imageUrl: "/images/products/0374_721733000159_patron-reposado-teq-80.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Patron",
    displaySize: "750ml",
  },
  {
    slug: "smirnoff-vodka-750ml-smooth-classic",
    title: "Smirnoff Vodka 750ml",
    category: "Vodka",
    price: "$16.19",
    badge: "Popular",
    description: "Smirnoff No. 21 Vodka is triple distilled and ten times filtered for exceptional smoothness. Perfect for classic cocktails like Moscow Mule or Martini. This 750ml bottle offers great value for any home bar or gathering.",
    imageUrl: "/images/products/0378_082000790839_smirnoff.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Smirnoff",
    displaySize: "750ml",
  },
  {
    slug: "smirnoff-vodka-750ml-smooth-classic-2",
    title: "Smirnoff Vodka 750ml - Smooth & Classic",
    category: "Vodka",
    price: "$16.19",
    badge: "Popular",
    description: "Smirnoff Vodka is a classic, triple-distilled spirit known for its smooth, clean taste. Perfect for cocktails or sipping neat, this 750ml bottle offers exceptional quality at a great value. A versatile staple for any home bar.",
    imageUrl: "/images/products/0379_082000778639_smirnoff.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Smirnoff",
    displaySize: "750ml",
  },
  {
    slug: "smirnoff-vodka-750ml-smooth-classic-3",
    title: "Smirnoff Vodka 750ml",
    category: "Vodka",
    price: "$16.19",
    badge: "Popular",
    description: "Smirnoff Vodka delivers a smooth, clean taste perfect for any occasion. Triple distilled and ten times filtered, this 750ml bottle offers exceptional quality at a great value. Ideal for classic cocktails or sipping neat.",
    imageUrl: "/images/products/0380_082000790808_smirnoff.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Smirnoff",
    displaySize: "750ml",
  },
  {
    slug: "smirnoff-triple-distilled-vodka-750ml",
    title: "Smirnoff Triple Distilled Vodka 750ml",
    category: "Vodka",
    price: "$16.19",
    badge: "Popular",
    description: "Smirnoff Triple Distilled Vodka delivers a smooth, clean taste perfect for cocktails or sipping. Crafted with a time-honored triple distillation process, this 750ml bottle offers exceptional clarity and a crisp finish. Ideal for any occasion, it’s a versatile spirit that elevates your favorite mixed drinks.",
    imageUrl: "/images/products/0382_082000000068_smirnoff-triple-destilled.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Smirnoff",
    displaySize: "750ml",
  },
  {
    slug: "1800-blanco-tequila-750ml",
    title: "1800 Blanco Tequila 750ml",
    category: "Tequila",
    price: "$31.19",
    badge: "Popular",
    description: "1800 Blanco is a crystal-clear, premium tequila made from 100% blue Weber agave. Its smooth, clean taste features hints of sweet agave, citrus, and a peppery finish. Perfect for sipping neat or elevating your favorite cocktails like margaritas and palomas.",
    imageUrl: "/images/products/0384_811538010139_1800-blanco.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "1800",
    displaySize: "750ml",
  },
  {
    slug: "casamigos-reposado-tequila-375ml-buy-online",
    title: "Casamigos Reposado Tequila 375ml",
    category: "Tequila",
    price: "$23.63",
    badge: "Popular",
    description: "Casamigos Reposado Tequila offers a smooth, rich taste with hints of caramel and vanilla. Aged for months in American white oak barrels, this 375ml bottle delivers a premium sipping experience perfect for cocktails or neat enjoyment.",
    imageUrl: "/images/products/0392_083089451352_casamigos-reposado.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 375,
    abv: 40,
    vendor: "Casamigos",
    displaySize: "375ml",
  },
  {
    slug: "don-julio-anejo-tequila-375ml-premium-aged-tequila",
    title: "Don Julio Anejo Tequila 375ml",
    category: "Tequila",
    price: "$27.41",
    badge: "Popular",
    description: "Don Julio Anejo is a premium tequila aged 18 months in American white oak barrels. It offers a rich, smooth taste with notes of caramel, vanilla, and toasted oak. Perfect for sipping neat or elevating classic cocktails. 375ml bottle.",
    imageUrl: "/images/products/0393_674545000612_don-julio-anejo.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 375,
    abv: 40,
    vendor: "Don",
    displaySize: "375ml",
  },
  {
    slug: "ciroc-apple-vodka-750ml-premium-french-vodka",
    title: "Ciroc Apple Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Apple vodka delivers a crisp, juicy apple taste with a smooth finish. Distilled from fine French grapes, this 750ml bottle offers a refreshing twist for cocktails or sipping neat. Perfect for any occasion.",
    imageUrl: "/images/products/0402_088076180451_ciroc-apple.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-peach-vodka-750ml-premium-flavored-vodka",
    title: "Ciroc Peach Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Peach Vodka delivers a lush, juicy peach flavor with a smooth, refined finish. Distilled from fine French grapes, this 750ml bottle offers a sophisticated twist for cocktails or sipping neat. Perfect for summer spritzers or peach martinis.",
    imageUrl: "/images/products/0403_088076177406_ciroc-peach.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-limonata-vodka-750ml-premium-lemon-flavored-vodka",
    title: "Ciroc Limonata Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Limonata is a premium vodka infused with vibrant lemon essence, crafted from fine French grapes. Its smooth, refreshing citrus profile makes it perfect for crisp cocktails or sipping chilled. A sophisticated choice for those who appreciate bright, zesty flavors in a luxurious spirit.",
    imageUrl: "/images/products/0404_088076189195_ciroc-limonata.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "absolut-elyx-vodka-750ml-luxury-swedish-vodka",
    title: "Absolut Elyx Vodka 750ml",
    category: "Vodka",
    price: "$34.99",
    badge: "Popular",
    description: "Absolut Elyx is a luxury Swedish vodka crafted from single-estate winter wheat and distilled in a vintage copper column still. Silky smooth with a rich, clean taste, it elevates any cocktail. Perfect for sipping neat or in premium mixed drinks.",
    imageUrl: "/images/products/0413_835229000711_absolut-elyx.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 750,
    abv: 40,
    vendor: "Absolut",
    displaySize: "750ml",
  },
  {
    slug: "johnnie-walker-red-label-1-75-l-buy-whiskey-online",
    title: "Johnnie Walker Red Label 1.75 L",
    category: "Whiskey",
    price: "$49.39",
    badge: "Popular",
    description: "Johnnie Walker Red Label is a bold, versatile Scotch whisky with a vibrant blend of up to 35 malt and grain whiskies. Its distinctive smoky and spicy character makes it perfect for mixing in classic cocktails like the Highball or enjoying on the rocks. A timeless choice for any occasion.",
    imageUrl: "/images/products/0338_088076163164_johnnie-walker-red-label.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 1750,
    abv: 40,
    vendor: "Johnnie",
    displaySize: "1.75L",
  },
  {
    slug: "chivas-regal-12-year-old-blended-scotch-whisky-750ml",
    title: "Chivas Regal 12 Year Old Blended Scotch Whisky 750ml",
    category: "Whiskey",
    price: "$37.43",
    badge: "Popular",
    description: "Chivas Regal 12 Year Old is a smooth, rich blended Scotch whisky with notes of honey, ripe apple, and vanilla. Aged for 12 years, it delivers a generous, creamy taste and a long, warm finish. Perfect for sipping neat or in classic cocktails.",
    imageUrl: "/images/products/0339_080432400395_chivas-regal.png",
    rating: 4.8,
    reviewCount: 199,
    volumeMl: 750,
    abv: 40,
    vendor: "Chivas",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-summer-watermelon-vodka-750ml",
    title: "Ciroc Summer Watermelon Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "CIROC Summer Watermelon vodka delivers a refreshing burst of juicy watermelon flavor, crafted with premium French grapes. Smooth and vibrant, it's perfect for summer cocktails or sipping chilled. Enjoy the taste of sun-ripened watermelon in every sip.",
    imageUrl: "/images/products/0440_088076183728_ciroc-summer-watermelon.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-vodka-750ml-premium-french-grape-vodka",
    title: "Ciroc Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Vodka is distilled five times from fine French grapes for an exceptionally smooth, crisp taste. This 750ml bottle delivers a clean finish with subtle citrus notes, perfect for sipping neat or elevating your favorite cocktails.",
    imageUrl: "/images/products/0441_088076185395_ciroc.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-pineapple-vodka-750ml-buy-online",
    title: "Ciroc Pineapple Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Pineapple vodka delivers a smooth, tropical twist on premium French vodka. Distilled from fine French grapes and infused with pineapple and other natural flavors, it offers a lush, juicy taste perfect for refreshing cocktails or sipping neat.",
    imageUrl: "/images/products/0442_088076179080_ciroc-pineapple.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-red-berry-vodka-750ml-premium-flavored-vodka",
    title: "Ciroc Red Berry Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Red Berry blends French vodka with ripe raspberry and strawberry flavors for a smooth, refreshing taste. Perfect for cocktails or sipping neat, this 750ml bottle delivers a vibrant berry experience with Ciroc's signature elegance.",
    imageUrl: "/images/products/0443_088076175051_ciroc-red-berry.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-vodka-750ml-premium-french-vodka",
    title: "Ciroc Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Vodka is a premium spirit distilled from fine French grapes, offering a smooth, crisp taste with subtle citrus notes. Perfect for sipping neat or elevating your favorite cocktails, this 750ml bottle brings a touch of luxury to any occasion.",
    imageUrl: "/images/products/0444_088076161863_ciroc-vodka.png",
    rating: 4.7,
    reviewCount: 197,
    volumeMl: 750,
    abv: 40,
    vendor: "Ciroc",
    displaySize: "750ml",
  },
  {
    slug: "ciroc-passion-vodka-750ml-tropical-fruit-flavored-vodka",
    title: "Ciroc Passion Vodka 750ml",
    category: "Vodka",
    price: "$35.69",
    badge: "Popular",
    description: "Ciroc Passion is a premium vodka infused with exotic tropical fruit flavors. Distilled from fine French grapes, it delivers a smooth, vibrant taste with notes of passion fruit and other tropical essences. Perfect for crafting refreshing cocktails or enjoying on the rocks.",
    imageUrl: "/images/products/0445_088076187399_ciroc-passion.png",
    rating: 4.7,
    reviewCount: 197,
    abv: 40,
    vendor: "Ciroc",
  },
  {
    slug: "busch-light-beer-25-oz-can-crisp-refreshing",
    title: "Busch Light Beer 25 oz Can - Crisp & Refreshing",
    category: "Beer",
    price: "$2.89",
    badge: "Popular",
    description: "Busch Light Beer in a 25 oz can delivers a crisp, refreshing taste with fewer calories. Perfect for casual gatherings, tailgates, or relaxing at home. Enjoy the smooth, light-bodied lager that's easy to drink and always satisfying.",
    imageUrl: "/images/products/0513_018200250040_busch-light-beer.png",
    rating: 4.7,
    reviewCount: 195,
    abv: 5,
    vendor: "Busch",
  },
  {
    slug: "jose-cuervo-gold-tequila-200ml-blue-agave",
    title: "Jose Cuervo Gold Tequila 200ml",
    category: "Tequila",
    price: "$7.99",
    badge: "Popular",
    description: "Jose Cuervo Gold is a blend of reposado and younger tequilas, crafted from blue agave. Its smooth, balanced character makes it perfect for margaritas, shots, or sipping. This 200ml bottle is ideal for trying or gifting.",
    imageUrl: "/images/products/0419_811538010924_jose-cuervo-tequila-gold-blue-agave.png",
    rating: 4.8,
    reviewCount: 198,
    volumeMl: 200,
    abv: 40,
    vendor: "Jose",
    displaySize: "200ml",
  },
]
